# Generated by Django 5.0.6 on 2024-07-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='diff',
            field=models.CharField(default='easy', max_length=100),
        ),
    ]
