# Generated by Django 5.0.6 on 2024-07-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problems_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='diff',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=100),
        ),
    ]
