# Generated by Django 5.0.6 on 2024-07-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problems_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='test_cases',
            name='problem_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
