# Generated by Django 5.0.6 on 2024-07-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problems_problem_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_cases',
            name='test_input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test_cases',
            name='test_output',
            field=models.TextField(),
        ),
    ]
