# Generated by Django 5.0.6 on 2024-07-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='user_id',
        ),
    ]
